name: GitHub Pages
permissions:
    id-token: write
    pages: write
on:
    push:
        branches: ['master']

jobs:
    build:
        runs-on: ubuntu-latest

        strategy:
            matrix:
                node-version: [16.x]

        steps:
            - uses: actions/checkout@v3
            - name: Use Node.js ${{ matrix.node-version }}
              uses: actions/setup-node@v3
              with:
                  node-version: ${{ matrix.node-version }}
                  cache: 'npm'

            - run: npm install --global yarn@latest
            - run: yarn --frozen-lockfile
            - run: yarn build
            - run: |
                  tar \
                    --dereference --hard-dereference \
                    --directory dist \
                    -cvf build.tar \
                    --exclude=.git \
                    --exclude=.github \
                    .
            - name: Upload a Build Artifact
              uses: actions/upload-artifact@v3.1.0
              with:
                  name: github-pages-artifact
                  path: build.tar
                  if-no-files-found: error

    deploy:
        runs-on: ubuntu-latest
        needs: [build]
        environment:
            name: github-pages
            url: ${{ steps.deployment.outputs.page_url }}

        steps:
            - uses: actions/deploy-pages@v1.2.1
              id: deployment
              with:
                  artifact_name: github-pages-artifact
